version: '3'

services:
  # source database
  crdv1:
    image: crdv
    ports:
      - 5401:5432
      - 5501:5433
      - 8001:8087
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
    command: cron -f
    cap_add:
      - "NET_RAW"
      - "NET_ADMIN"
  crdv2:
    image: crdv
    ports:
      - 5402:5432
      - 5502:5433
      - 8002:8087
    command: cron -f
  crdv3:
    image: crdv
    ports:
      - 5403:5432
      - 5503:5433
      - 8003:8087
    command: cron -f
